version: '3.8'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
    # Repositar variables de entorno es mala praxis
      - ./env_files/grafana.env
    networks:
      - demo

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - demo

  portainer:
    image: portainer/portainer
    container_name: portainer
    networks:
      - demo

  cadvisor:
    image: gcr.io/google_containers/cadvisor
    container_name: cadvisor
    networks:
     - demo

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - demo

  elastic:
    image: elasticsearch
    container_name: elastic
    networks:
      - demo

  fluentbit:
    image:
    container_name:
    networks:
      - demo

networks:
  demo: