version: '3.8'
# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml --> Plantilla interesante para prometheus
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    #env_file:
    ## Repositar variables de entorno es mala praxis
    #  - ./env_files/grafana.env
    user: "1000" #Cambiar por $(id -u)

    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - demo
    logging:
      driver: "fluentd"
    depends_on:
      - kibana

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - elasticsearch
    logging:
      driver: "fluentd"
    networks:
      - demo

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8000:8000
    environment:
      - HTTP_PROXY=portainer.test.rafa.com
    networks:
      - demo
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "fluentd"

    depends_on:
      - fluent-bit

  cadvisor:
    image: gcr.io/google_containers/cadvisor
    container_name: cadvisor
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
     - demo

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./env_files/:/etc/prometheus/
    depends_on:
      - cadvisor
    #logging: NO SOPORTADO
    #  driver: "fluentd"
    networks:
      - demo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - ./elastic_data/:/usr/share/elasticsearch/data
    networks:
      - demo
    logging:
      driver: "fluentd"
    depends_on:
      - fluent-bit
# Kibana siempre ha de tener la misma versión que elasticsearch
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.10.2"
    env_file:
      - env_files/kibana.env
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - demo
    logging:
      driver: "fluentd"
    depends_on:
      - elasticsearch

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - ./env_files/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - cadvisor
    networks:
      - demo

networks:
  demo: