version: '3.8'
# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml --> Plantilla interesante para prometheus
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
    # Repositar variables de entorno es mala praxis
      - ./env_files/grafana.env
    networks:
      - demo
    depends_on:
      - prometheus

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - grafana
    networks:
      - demo

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8000:8000
    environment:
      - HTTP_PROXY=portainer.test.rafa.com
    networks:
      - demo
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  cadvisor:
    image: gcr.io/google_containers/cadvisor
    container_name: cadvisor
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
     - demo

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./env_files/:/etc/prometheus/
    depends_on:
      - cadvisor
    networks:
      - demo

  elastic:
    image: elasticsearch
    container_name: elastic
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - demo

  fluentd:
    image: fluent/fluentd
    container_name: fluentd
    volumes:
      - ./env_files/:/fluentd/etc
    depends_on:
      - elastic
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    networks:
      - demo

networks:
  demo: